spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: true
  jpa:

    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


# application-prod.yml
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  secretKey: bvffjk@123