export const projectList = [
    {
      id: 1,
      name: "Trung tâm thương mại Plaza",
      address: "126 Đ. Hồng Bàng, Phường 12, Quận 5, Hồ Chí Minh",
      status: "Hoàn thành",
      startDate: "01/01/2025",
      endDate: "01/10/2025",
      investor: "Công ty TNHH Xây dựng ABC",
      progress: 65,
      type: "Dân dụng",
      budget: "$200,000,000",
    },
    {
      id: 2,
      name: "Trung tâm thương mại Plaza",
      address: "126 Đ. Hồng Bàng, Phường 12, Quận 5, Hồ Chí Minh",
      status: "Tạm dừng",
      startDate: "01/01/2025",
      endDate: "01/10/2025",
      investor: "Công ty TNHH Xây dựng ABC",
      progress: 65,
      type: "Dân dụng",
      budget: "$200,000,000",
    },
    {
      id: 3,
      name: "Trung tâm thương mại Plaza",
      address: "126 Đ. Hồng Bàng, Phường 12, Quận 5, Hồ Chí Minh",
      status: "Đang thi công",
      startDate: "01/01/2025",
      endDate: "01/10/2025",
      investor: "Công ty TNHH Xây dựng ABC",
      progress: 65,
      type: "Dân dụng",
      budget: "$200,000,000",
    },
    {
      id: 4,
      name: "Trung tâm thương mại Plaza",
      address: "126 Đ. Hồng Bàng, Phường 12, Quận 5, Hồ Chí Minh",
      status: "Đang thi công",
      startDate: "01/01/2025",
      endDate: "01/10/2025",
      investor: "Công ty TNHH Xây dựng ABC",
      progress: 65,
      type: "Dân dụng",
      budget: "$200,000,000",
    },
  ];