spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thicong
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
