server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qltc
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

