server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/QLCTXD
    username: postgres
    password: 2012628
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# Add this to your application.yaml or application-dev.yaml
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
